;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-kill-whole-line
        crux-move-beginning-of-line
        crux-smart-kill-line
        crux-top-join-line
        erlang-electric-comma
        erlang-electric-lt
        eval-print-last-sexp
        indent-for-tab-command
        kill-region
        org-delete-char
        org-self-insert-command
        xterm-paste
        ))

(setq mc/cmds-to-run-once
      '(
        avy-goto-line
        erlang-electric-gt
        erlang-electric-semicolon
        find-file
        keyboard-escape-quit
        my/new-shell-in-new-window
        org-agenda
        org-agenda-append-agenda
        org-agenda-date-prompt
        org-agenda-next-line
        org-agenda-switch-to
        org-timer-set-timer
        other-frame
        suspend-frame
        swiper
        ))
